baseurl = "httpgs://evanklemen.com/"
title = "Evan Klemen"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Evan Klemen"
  description = "I mean, it's already broken..."
  logo = "fa-diamond"
  copyright = "Untitled"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "Evan Klemen"